// Generated by gencpp from file gatlin/ActionRequest.msg
// DO NOT EDIT!


#ifndef GATLIN_MESSAGE_ACTIONREQUEST_H
#define GATLIN_MESSAGE_ACTIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gatlin
{
template <class ContainerAllocator>
struct ActionRequest_
{
  typedef ActionRequest_<ContainerAllocator> Type;

  ActionRequest_()
    : action()
    , args()  {
    }
  ActionRequest_(const ContainerAllocator& _alloc)
    : action(_alloc)
    , args(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _action_type;
  _action_type action;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _args_type;
  _args_type args;




  typedef boost::shared_ptr< ::gatlin::ActionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gatlin::ActionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ActionRequest_

typedef ::gatlin::ActionRequest_<std::allocator<void> > ActionRequest;

typedef boost::shared_ptr< ::gatlin::ActionRequest > ActionRequestPtr;
typedef boost::shared_ptr< ::gatlin::ActionRequest const> ActionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gatlin::ActionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gatlin::ActionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gatlin

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'gatlin': ['/home/cs4752/ros_ws/src/gatlin/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gatlin::ActionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gatlin::ActionRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gatlin::ActionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gatlin::ActionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gatlin::ActionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gatlin::ActionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gatlin::ActionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4b94e6beb55c7450b4d7bc3566e02700";
  }

  static const char* value(const ::gatlin::ActionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4b94e6beb55c7450ULL;
  static const uint64_t static_value2 = 0xb4d7bc3566e02700ULL;
};

template<class ContainerAllocator>
struct DataType< ::gatlin::ActionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gatlin/ActionRequest";
  }

  static const char* value(const ::gatlin::ActionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gatlin::ActionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string action\n\
string args\n\
";
  }

  static const char* value(const ::gatlin::ActionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gatlin::ActionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action);
      stream.next(m.args);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ActionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gatlin::ActionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gatlin::ActionRequest_<ContainerAllocator>& v)
  {
    s << indent << "action: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.action);
    s << indent << "args: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.args);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GATLIN_MESSAGE_ACTIONREQUEST_H
