// Generated by gencpp from file gatlin/Action.msg
// DO NOT EDIT!


#ifndef GATLIN_MESSAGE_ACTION_H
#define GATLIN_MESSAGE_ACTION_H

#include <ros/service_traits.h>


#include <gatlin/ActionRequest.h>
#include <gatlin/ActionResponse.h>


namespace gatlin
{

struct Action
{

typedef ActionRequest Request;
typedef ActionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Action
} // namespace gatlin


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gatlin::Action > {
  static const char* value()
  {
    return "65dca9bb9da789498b2c2eaf09051d97";
  }

  static const char* value(const ::gatlin::Action&) { return value(); }
};

template<>
struct DataType< ::gatlin::Action > {
  static const char* value()
  {
    return "gatlin/Action";
  }

  static const char* value(const ::gatlin::Action&) { return value(); }
};


// service_traits::MD5Sum< ::gatlin::ActionRequest> should match 
// service_traits::MD5Sum< ::gatlin::Action > 
template<>
struct MD5Sum< ::gatlin::ActionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gatlin::Action >::value();
  }
  static const char* value(const ::gatlin::ActionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gatlin::ActionRequest> should match 
// service_traits::DataType< ::gatlin::Action > 
template<>
struct DataType< ::gatlin::ActionRequest>
{
  static const char* value()
  {
    return DataType< ::gatlin::Action >::value();
  }
  static const char* value(const ::gatlin::ActionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gatlin::ActionResponse> should match 
// service_traits::MD5Sum< ::gatlin::Action > 
template<>
struct MD5Sum< ::gatlin::ActionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gatlin::Action >::value();
  }
  static const char* value(const ::gatlin::ActionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gatlin::ActionResponse> should match 
// service_traits::DataType< ::gatlin::Action > 
template<>
struct DataType< ::gatlin::ActionResponse>
{
  static const char* value()
  {
    return DataType< ::gatlin::Action >::value();
  }
  static const char* value(const ::gatlin::ActionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GATLIN_MESSAGE_ACTION_H
