// Generated by gencpp from file gatlin/MoveRobot.msg
// DO NOT EDIT!


#ifndef GATLIN_MESSAGE_MOVEROBOT_H
#define GATLIN_MESSAGE_MOVEROBOT_H

#include <ros/service_traits.h>


#include <gatlin/MoveRobotRequest.h>
#include <gatlin/MoveRobotResponse.h>


namespace gatlin
{

struct MoveRobot
{

typedef MoveRobotRequest Request;
typedef MoveRobotResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveRobot
} // namespace gatlin


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gatlin::MoveRobot > {
  static const char* value()
  {
    return "6d43e0bb64402a557ab604147d2f9e11";
  }

  static const char* value(const ::gatlin::MoveRobot&) { return value(); }
};

template<>
struct DataType< ::gatlin::MoveRobot > {
  static const char* value()
  {
    return "gatlin/MoveRobot";
  }

  static const char* value(const ::gatlin::MoveRobot&) { return value(); }
};


// service_traits::MD5Sum< ::gatlin::MoveRobotRequest> should match 
// service_traits::MD5Sum< ::gatlin::MoveRobot > 
template<>
struct MD5Sum< ::gatlin::MoveRobotRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gatlin::MoveRobot >::value();
  }
  static const char* value(const ::gatlin::MoveRobotRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gatlin::MoveRobotRequest> should match 
// service_traits::DataType< ::gatlin::MoveRobot > 
template<>
struct DataType< ::gatlin::MoveRobotRequest>
{
  static const char* value()
  {
    return DataType< ::gatlin::MoveRobot >::value();
  }
  static const char* value(const ::gatlin::MoveRobotRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gatlin::MoveRobotResponse> should match 
// service_traits::MD5Sum< ::gatlin::MoveRobot > 
template<>
struct MD5Sum< ::gatlin::MoveRobotResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gatlin::MoveRobot >::value();
  }
  static const char* value(const ::gatlin::MoveRobotResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gatlin::MoveRobotResponse> should match 
// service_traits::DataType< ::gatlin::MoveRobot > 
template<>
struct DataType< ::gatlin::MoveRobotResponse>
{
  static const char* value()
  {
    return DataType< ::gatlin::MoveRobot >::value();
  }
  static const char* value(const ::gatlin::MoveRobotResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GATLIN_MESSAGE_MOVEROBOT_H
