// Generated by gencpp from file seam/MoveArmRequest.msg
// DO NOT EDIT!


#ifndef SEAM_MESSAGE_MOVEARMREQUEST_H
#define SEAM_MESSAGE_MOVEARMREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace seam
{
template <class ContainerAllocator>
struct MoveArmRequest_
{
  typedef MoveArmRequest_<ContainerAllocator> Type;

  MoveArmRequest_()
    : arm(0)
    , pos()
    , in_plane(false)  {
    }
  MoveArmRequest_(const ContainerAllocator& _alloc)
    : arm(0)
    , pos(_alloc)
    , in_plane(false)  {
  (void)_alloc;
    }



   typedef uint32_t _arm_type;
  _arm_type arm;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _pos_type;
  _pos_type pos;

   typedef uint8_t _in_plane_type;
  _in_plane_type in_plane;




  typedef boost::shared_ptr< ::seam::MoveArmRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::seam::MoveArmRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MoveArmRequest_

typedef ::seam::MoveArmRequest_<std::allocator<void> > MoveArmRequest;

typedef boost::shared_ptr< ::seam::MoveArmRequest > MoveArmRequestPtr;
typedef boost::shared_ptr< ::seam::MoveArmRequest const> MoveArmRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::seam::MoveArmRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::seam::MoveArmRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace seam

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::seam::MoveArmRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::seam::MoveArmRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::seam::MoveArmRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::seam::MoveArmRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::seam::MoveArmRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::seam::MoveArmRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::seam::MoveArmRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e24b721fc7f28e59470f8a8ede52db77";
  }

  static const char* value(const ::seam::MoveArmRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe24b721fc7f28e59ULL;
  static const uint64_t static_value2 = 0x470f8a8ede52db77ULL;
};

template<class ContainerAllocator>
struct DataType< ::seam::MoveArmRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "seam/MoveArmRequest";
  }

  static const char* value(const ::seam::MoveArmRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::seam::MoveArmRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
uint32 arm\n\
geometry_msgs/Point pos\n\
bool in_plane\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::seam::MoveArmRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::seam::MoveArmRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.arm);
      stream.next(m.pos);
      stream.next(m.in_plane);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct MoveArmRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::seam::MoveArmRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::seam::MoveArmRequest_<ContainerAllocator>& v)
  {
    s << indent << "arm: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.arm);
    s << indent << "pos: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.pos);
    s << indent << "in_plane: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.in_plane);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEAM_MESSAGE_MOVEARMREQUEST_H
