(cl:defpackage gatlin-srv
  (:use )
  (:export
   "MOVEROBOT"
   "<MOVEROBOT-REQUEST>"
   "MOVEROBOT-REQUEST"
   "<MOVEROBOT-RESPONSE>"
   "MOVEROBOT-RESPONSE"
   "ACTION"
   "<ACTION-REQUEST>"
   "ACTION-REQUEST"
   "<ACTION-RESPONSE>"
   "ACTION-RESPONSE"
  ))

